apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: covid-demo
  template:
    metadata:
      labels:
        app: covid-demo
    spec:
      containers:
      - name: covid-demo
        image: doyunii/mybox
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8090
        env: 
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: name
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: user
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: password
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8090
          initialDelaySeconds: 60
          timeoutSeconds: 15
          periodSeconds: 60
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8090
          initialDelaySeconds: 30
          timeoutSeconds: 2
          periodSeconds: 30
          failureThreshold: 3